version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - service-network
    environment:
      - MONGO_INITDB_DATABASE=servicedb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  service-api:
    build:
      context: ./service-api
      dockerfile: Dockerfile
    container_name: service-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/servicedb
    networks:
      - service-network
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  service-client:
    build:
      context: ./service-client
      dockerfile: Dockerfile
    container_name: service-client
    ports:
      - "8081:8081"
    environment:
      - ACTIVE_PROFILE=docker
    volumes:
      - ./service-client/config:/config:ro
    networks:
      - service-network
    depends_on:
      - service-api
    restart: unless-stopped

networks:
  service-network:
    driver: bridge

volumes:
  mongodb_data: 