version: '3.8'

services:
  service-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/servicedb
    networks:
      - service-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - service-network
    environment:
      - MONGO_INITDB_DATABASE=servicedb

networks:
  service-network:
    driver: bridge

volumes:
  mongodb_data:
