server:
  host: "0.0.0.0"
  port: 8081
serviceApiClient:
  host: "http://service-api:8080"  
  maxConnexions: 200
  timeout: 3s
  circuitBreaker:
    name: "serviceApiClient"
    maxRequests: 10
    interval: 30s
    timeout: 10s
    requestsVolumeThreshold: 20
    failureThreshold: 0.5

